### ISSUE TITLE
Log Clean Issue: Circle Bot

### ISSUE THREAD

**Issue by DracoClaw** [PluralKit/PluralKit#421]
The reference to the Circle Bot logs is looking at the wrong part of the embed. Its looking at the author field when it should be looking at the Description. Additionally, Circle's logs have `Message from @User deleted in #channel` in the description. The code is checking if the message starts with `Message deleted in`. 

https://github.com/xSke/PluralKit/blob/6a4033b2a9a0b7e0a9c6a59b4596ef83c7d94e91/PluralKit.Bot/Services/LoggerCleanService.cs#L251

**Comment by spiralw** [comment]
#427:
> Closing this as Circle now natively supports PluralKit

closing this issue as well
