### ISSUE TITLE
Prevent member ID collision with member names

### ISSUE THREAD

**Issue by sisby-folk** [PluralKit/PluralKit#475]
Hi hello there!

Currently, when in a system with a member that has a five letter name (e.g. `steve`), typing `pk;m steve` will bring up the member from another system with the 5 letter member ID `steve`

While it's critical to be able to access any member by ID, this affects basic operation for any member with a 5 letter name.

I'm not sure if `pk;m` already has explicit identifier flags like `pk;m --id steve` / `pk;m --name steve`, but one solution would be to implement these, and then swap the prioritization of `pk;m` back to members of the command runner's system.

**Comment by xSke** [comment]
`pk;m` will already prioritize a member name in your own system over an ID in someone else's.

**Comment by Draconizations** [comment]
`pk;m steve -id` also already exists. A `-name` flag does not exist due to the reason mentioned above.

**Comment by sisby-folk** [comment]
huh! okay - for a bit I thought this was a case sensitivity issue, or something funny with renaming to ids, but honestly I don't know _what_  caused this confusion at all - all good then!
