### ISSUE TITLE
Dashboard requests open-dyslexic font over HTTP, resulting in a failure to load it entirely

### ISSUE THREAD

**Issue by ArcanaOfSouls** [PluralKit/PluralKit#485]
The Dashboard attempts to load the `open-dyslexic` font via the following URL: http://fonts.cdnfonts.com/css/open-dyslexic

That file is referenced at [dashboard/styles/generic.scss on line 6](https://github.com/PluralKit/PluralKit/blob/main/dashboard/styles/generic.scss#L6)

This results in an error in most modern browsers due to [mixed active content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#mixed_active_content) being disallowed by default for security reasons.

```text
dash.pluralkit.me/:1 Mixed Content: The page at 'https://dash.pluralkit.me/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.cdnfonts.com/css/open-dyslexic'. This request has been blocked; the content must be served over HTTPS.
```

We're opening a pull request to update the URL to its HTTPS equivalent momentarily, but we wanted to make sure the issue was in place first.

The URL will be changed to: https://fonts.cdnfonts.com/css/open-dyslexic

**Comment by spiralw** [comment]
@Draconizations is there any reason why this file isn't censored?

**Comment by spiralw** [comment]
er, vendored, autocorrect oops...

**Comment by Draconizations** [comment]
It honestly might be better to vendor it, yeah. Same with some other files that we use for highlight.js right now.

(the reason is just... "I wanted to get it working quickly and took bad shortcuts thanks to it")
