### ISSUE TITLE
Explain plurality more in the website

### ISSUE THREAD

**Issue by Madis0** [PluralKit/PluralKit#493]
The website should explain the whole concept of the bot's target audience more than it does now. I'm not that experienced in the concept to do it myself though, so I hope someone else can.

**Comment by rladenson** [comment]
This has been requested before and considered, however anything beyond the basics of "multiple people in one body" starts getting controversial as plurals are very diverse. If someone else wants to suggest something we can consider it but we haven't been able to come up with a more elaborated version that makes sense.

**Comment by Madis0** [comment]
Then how about just linking to sources that can explain it? E.g. https://morethanone.info

**Comment by Draconizations** [comment]
Linking to sources still leaves us with the same issue, unfortunately. Some people will want a different explanation of plurality than others, and some people will want a source that others want left out. Linking a source means that we endorse everything that source states, which we cannot satisfy everyone’s needs with.
