### ISSUE TITLE
PluralKit demands Manage Webhooks permission despite having it

### ISSUE THREAD

**Issue by elkay235** [PluralKit/PluralKit#496]
A bit of a weird issue. I cloned the most recent commit to test before I committed to updating my private fork of PluralKit (for use between me and a few others). Made a fresh testing Postgres database, and ran through the generic steps for making a member...

Trying to use the member I created informs me that it does not have _Manage Webhooks._ Odd. Despite it having administrator permissions, I gave both its role and the role in the channel permission and try again. Doesn't work.

The bot console prints nothing unusual from what I can see. It's as if it is running as intended unless I missed something. I attached Discord messages as images and a copy of the log.
![image](https://user-images.githubusercontent.com/68518964/201442223-bab0e8da-8b8b-4156-b38f-95c78117dfd7.png)
[log.txt](https://github.com/PluralKit/PluralKit/files/9993589/log.txt)

**Comment by spiralw** [comment]
did you set the bot's client id in `pluralkit.conf`? off the top of my head, it needs that set to calculate permissions correctly. it's possible i forgot to update the documentation when i made the change in the code

**Comment by elkay235** [comment]
> 

That did it. I probably got confused since the `PluralKit.Bot.ClientId` field was labeled as optional, last I checked that is. Thank you for the help.
