### ISSUE TITLE
PK proxying doesn't work in one server.

### ISSUE THREAD

**Issue by lilac777** [PluralKit/PluralKit#509]
Hello! I have used PK for a year for a private server of ours and the commands work fine (pk;system, pk;member ___ etc) however the proxying for members no longer works in this server.

We are on a mobile device, an android in specific and have no idea how to fix it :( we've cleared discord cache, and even deleted the app and reinstalled it

**Comment by lilac777** [comment]
![Screenshot_20221224-205434_Discord](https://user-images.githubusercontent.com/121373145/209459023-a7b3c8ef-8d6d-4ad4-917e-c1e281a0cb72.jpg)
example of the issue i'm facing

also checked perms for pk, they're all enabled

**Comment by u1f408** [comment]
Hiya! This is something that we would be better able to help with [in the PluralKit support Discord server](https://discord.gg/PczBt78) 😸

**Comment by lilac777** [comment]
I did that aswell and no response, but thank you either way :)

**Comment by u1f408** [comment]
If you don't get a response in the support server at any point, feel free to ask your question again! PluralKit support staff are all volunteers, and we may not see every message in the support channels (especially during the end-of-year holiday period!).
