### ISSUE TITLE
everyone becoming one proxy name in servers

### ISSUE THREAD

**Issue by kirbyszy** [PluralKit/PluralKit#521]
After posting in a server, everyone who was proxying in that server will become one alter's proxy name. Its kinda bothering me so I thought to drop it in here and see what I can do, or if its a bug currently being worked on. 
![image](https://user-images.githubusercontent.com/126285283/221270117-783b0211-f99d-4d18-b18e-c0d3f5ba575e.png)
![image](https://user-images.githubusercontent.com/126285283/221270172-cdfde9aa-5e0c-4e37-9729-ac83518e44b5.png)
![image](https://user-images.githubusercontent.com/126285283/221270278-1e8d56c1-3492-434e-81b2-2fa85a922fa0.png)

**Comment by xSke** [comment]
This is an issue on Discord's end - they are aware of the bug and are working on a fix but they don't have anything rolled out yet. There's nothing we can do about it, sorry :/
