### ISSUE TITLE
Escape character so autoproxy doesnt have to be manually toggled for singular messages

### ISSUE THREAD

**Issue by RainNyte** [PluralKit/PluralKit#525]
Allow configuring a tag that can be included in a message that prevents the bot from proxying a message regardless of autoproxy settings or other tags included, because it is a hassle to have to jump channels, turn off autoproxy, and then jump back to send your message, then jump again to send it if you need to do something that requires nitro since the bot can't use your nitro permissions

**Comment by spiralw** [comment]
this already exists! you can start a message with a backslash (`\`) to stop a message from autoproxying. if you're using latch mode autoproxy, two backslashes "unlatch" the currently autoproxied member.
