### ISSUE TITLE
Escape [this](type.of.link)

### ISSUE THREAD

**Issue by Pokefan5** [PluralKit/PluralKit#536]
As of right now PluralKit allows using links [like this](https://github.com/PluralKit/PluralKit)
`[like this](https://github.com/PluralKit/PluralKit) `
in accordance to Markdown syntax.

This can both be unexpected and abused to mask links like this: [https://github.com](https://google.com)
`[https://github.com](https://google.com)`

The real link will only be revealed once the discord warning for external links pops up.

This could be simply escaped by detecting it via a RegEx and adding a `\` [like this]\(https://github.com/PluralKit/PluralKit)
`[like this]\(https://github.com/PluralKit/PluralKit)`

**Comment by u1f408** [comment]
The Discord link warning popup exists for a reason - we aren't going to deliberately break something that a lot of users have genuine uses for.
