### ISSUE TITLE
Allow reacting with :x: to delete non-proxied messages belonging to your account

### ISSUE THREAD

**Issue by Astralchroma** [PluralKit/PluralKit#549]
Kinda gotten used to reacting with :x: to delete messages, although there is the potential to mess up and try to do that on a non-proxied message.

Could be kinda nice if reacting to your own non-proxied messages (if your account has a system) would still delete them for those who are used to deleting using that method with proxied messages

**Comment by thetayloredman** [comment]
Not very good for if/when you try to do a vote and you react with :white_check_mark: and :x:

**Comment by u1f408** [comment]
This will not be implemented, sorry.
