### ISSUE TITLE
PluralKit doesn't support stage text channels.

### ISSUE THREAD

**Issue by BucketOfCompasses** [PluralKit/PluralKit#550]
![image](https://user-images.githubusercontent.com/5214513/236669711-6ae22580-9e47-460f-9c4b-ab1462b866e5.png)

https://github.com/PluralKit/PluralKit/blob/3bac8816d22a0a167b720ba8be053954ca5b61dd/PluralKit.Bot/Utils/DiscordUtils.cs#L222-L230

Not too familiar with the bot workings but might be as simple as adding:
```
Channel.ChannelType.GuildNewsThread or
Channel.ChannelType.GuildStageVoice;
```

Thought I'd make an issue in any case since I couldn't find any issue refering to stage channels.

**Comment by u1f408** [comment]
That addition is indeed all that's needed! Thanks for the report, will get this live shortly.
