### ISSUE TITLE
API endpoints for message proxying

### ISSUE THREAD

**Issue by Encode42** [PluralKit/PluralKit#552]
The ability to send proxied messages directly through PK's webhooks may result in a better experience for readers, as messages don't need to be re-sent.

An app can be made - *or* a client mod - that interacts with said endpoints to send messages through PK before they get to Discord. This would solve the issue of a jumpy chat, since of course, there's no messages to be deleted.

I'm not sure how this endpoint would functionally work, whether you'd authenticate with Discord first, generate a token through the bot or dashboard, etc. But I do believe this can be useful to get around some of Discord's limitations.

**Comment by rladenson** [comment]
This would also bypass automod and moderation bots :/

**Comment by granny** [comment]
> This would also bypass automod

Not if PluralKit respects the automod rules directly. The discord API has an endpoint for grabbing them: https://discord.com/developers/docs/resources/auto-moderation#list-auto-moderation-rules-for-guild

> and moderation bots :/

This would be a valid concern I guess, but I'm guessing that would already be an issue with PluralKit as it is? Excuse my ignorance since I don't directly use it myself.

**Comment by rladenson** [comment]
Currently PluralKit is compatible with modbots! It has a built in delay before it deletes the original message, and if that message is already gone when it goes to delete it (ie if a modbot deleted it) pk then deletes its proxied message.

**Comment by rladenson** [comment]
Whether modbot compatibility needs to stay around with automod being a thing now is above my pay grade XD

**Comment by u1f408** [comment]
There are a whole bunch of issues with doing this - mod bot compatibility is incredibly important (especially for things like SafeLink); Discord don't publish the regexes/wordsets used for the AutoMod presets (so we can't run those ourselves); plus this would also likely allow bypassing things like user timeouts in a server.

I agree on the premise of this: proxying messages without the delete/resend dance would be _incredibly_ nice - but this specific suggestion would not be feasible.
