### ISSUE TITLE
Text-to-speech support

### ISSUE THREAD

**Issue by zauberparacelsus** [PluralKit/PluralKit#561]
Would it be possible to add support for Discord's text-to-speech functionality, so that otherwise-nonverbal system members can use it to speak verbally?  Particular application I was thinking of was when using pluralkit in the text chat that runs alongside voice channels.

**Comment by rladenson** [comment]
I assume they want it to be proxied and tts, otherwise it wouldn't be a pluralkit issue. This is definitely possible, discord webhooks allow the tts option, it's mostly a question of how the UI would work

**Comment by rladenson** [comment]
@zauberparacelsus Do you have any ideas for how you'd want this to work? Ie, would your system enable it in specific channels for all members, for specific members everywhere, would the server moderators enable it for everyone in specific channels, or something else? (Note I'm not a main dev and I'm not guaranteeing things, just trying to get stuff clarified haha)

**Comment by zauberparacelsus** [comment]
Well, the way we think it would be activated would perhaps be by setting up TTS-specific proxy tags.  Like, as an example, my headmate Rubinda normaly uses the tag "R:text" for talking normally through a proxy, but hypothetically she could use the tag "R::text" or R:text --tts" as a proxy that uses TTS.

**Comment by rladenson** [comment]
Talked with u1f408 (the current main dev) in the discord-- unfortunately that exact method won't be possible. What we can (and will) do is have the "TTS on when available" be an option per-member. You'd then be able to either toggle this on or off as needed or make utility members with it turned on. 

(You're free to [join the discord](https://discord.gg/PczBt78) if you want to talk about this in more detail! (This isn't meant to be a passive aggressive way to say don't talk here, it's just an option))

**Comment by zauberparacelsus** [comment]
So, it wouldn't be possible on a per-message basis?  Because that sort of sounds like it would be all-or-nothing per member.

**Comment by rladenson** [comment]
Correct, it's not possible to designate different behavior based on which proxy tag is used or any other part of a non-command message

**Comment by thetayloredman** [comment]
Has Discord not completely removed /tts? I've never seen it used and tried it to no avail and now it doesn't even exist on my clients

**Comment by rladenson** [comment]
You need the "send text-to-speech messages" permission to use /tts, are you sure you're trying somewhere where you have that permission?

**Comment by zauberparacelsus** [comment]
@rladenson We just tested that after turning on the permissions, and it still did not work.

**Comment by rladenson** [comment]
@zauberparacelsus sorry, are you talking about it not working for proxied messages or nonproxied messages? My statement about needing to turn the tts permission on was about thetayloredman asking if discord has removed text to speech altogether

**Comment by zauberparacelsus** [comment]
@rladenson Ah, sorry about that.  And yeah, I was talking about proxied messages.

**Comment by thetayloredman** [comment]
Why not just `/tts text -A` and then have Discord do the tts while at the same time pk sees `text -A` and proxies it?

**Comment by thetayloredman** [comment]
/tts does nothing for me, on non-prox messages- @rladenson

**Comment by rladenson** [comment]
@thetayloredman 


> Why not just `/tts text -A` and then have Discord do the tts while at the same time pk sees `text -A` and proxies it?

Discord stops reading the message out when it's deleted-- all that happens in this case is "[base account name] said" and then it cuts off



> /tts does nothing for me, on non-prox messages- @rladenson

Please make sure that your computer sound is on, your discord is outputting sound to a valid speaker, and that in your discord accessibility settings you have "allow playback and use of /tts command" turned on. If these things don't help I cannot provide more troubleshooting support for this, please contact discord support instead.

**Comment by thetayloredman** [comment]
@rladenson Chances are I probably don't have a voice installed or something. I'm on Arch Linux and I don't even have stuff like a CJK or emoji font so I wouldn't be shocked.

That first point makes sense

**Comment by rladenson** [comment]
@zauberparacelsus this feature is in beta now
