### ISSUE TITLE
logclean support for Skyra?

### ISSUE THREAD

**Issue by thetayloredman** [PluralKit/PluralKit#581]
i believe this could be matched exact as well

**Comment by rladenson** [comment]
This does not have what's needed to be matched exactly unless there's an option to make logs more detailed that I'm not seeing.

**Comment by rladenson** [comment]
In order to be matched precisely we need the message ID of the deleted message to be shown in the log.

**Comment by thetayloredman** [comment]
@rladenson Yeah, nevermind. I thought the ID in the author portion was the message ID. However, there's a link in the embed somewhere that links to the channel, it could even be a message link (as I believe clicking on a message link with an invalid ID would take you to the closest message next to that ID and this appears to be the behavior)?

**Comment by thetayloredman** [comment]
The link in the top of the embed appears to be a message link as it brings me to that area of the channel

**Comment by rladenson** [comment]
![image](https://github.com/PluralKit/PluralKit/assets/78043712/1a8097e3-0b07-4407-82b7-c8287b0a9f3e)

I'm not seeing any link? Like I said before maybe there's an option I'm not seeing to add more stuff to logs ...? Do you know if that exists?

**Comment by thetayloredman** [comment]
Click on the portion containing the username and user ID. That's a message link as far as I can tell.

**Comment by rladenson** [comment]
@thetayloredman I asked in their support server, this is a discrepancy with how discord displays things on mobile vs desktop :p

**Comment by rladenson** [comment]
In beta bot now, will be pushed to main when other updates are #580
