### ISSUE TITLE
Add support for silent messages.

### ISSUE THREAD

**Issue by CrimsonFork** [PluralKit/PluralKit#596]
It would be nice if PK sent a silent message when the original one was, as well.

From our limited understanding of how it works, we think that in the message JSON at line 36, `"flags"` the value `4096` is the one that indicates a silent message.

**Comment by nim-ka** [comment]
It's nice for PluralKit to *not* do this though, because then you can send a message pinging someone as a silent message, and then when it proxies it doesn't give the person a duplicate ping

**Comment by rladenson** [comment]
Silent messages still ping so it still double pings with the current way things are

**Comment by rladenson** [comment]
Sidenote that we are (at some point) going to test having *all* PK messages be silent. No guarantees it gets through but we will test it on the beta bot at some point.

**Comment by CrimsonFork** [comment]
Closing the issue since it's now redundant.
