### ISSUE TITLE
Nitro emoji from other servers don't work.

### ISSUE THREAD

**Issue by CrimsonFork** [PluralKit/PluralKit#600]
It would appear in the documentation that it is supposed to be possible to do have PK use nitro emoji, but
![global permissions](https://cdn.discordapp.com/attachments/1193789213854941186/1198071385164099734/image.png?ex=65bd91ed&is=65ab1ced&hm=ccb0f83bf247f9d2e0630e3132aabb9f8eb73cb97844e0f99f2d2b6cffc78c8b&)
![channel permissions](https://cdn.discordapp.com/attachments/1193789213854941186/1198071483868659823/image.png?ex=65bd9204&is=65ab1d04&hm=f0587b5eb2beb3e916a64f96e61151327a12ef93125e450facea85b80aad0872&)
![message with failed emoji](https://github.com/PluralKit/PluralKit/assets/22666602/25a21e20-8f76-46db-a037-a30f2f582d12)
Unless We misunderstand what https://pluralkit.me/faq/#why-can-t-i-use-nitro-emoji-in-some-channels is supposed to be about.

**Comment by CrimsonFork** [comment]
Ah, yeah, suspected that was the case but it wasn't mentioned anywhere, so thought that maybe it's different for bots and webhooks, so would make sense. So, basically, the solution here would be to ask the servers in question to include PK?

**Comment by multimasks** [comment]
Yep, that's the recommended solution

(We do mention that PK must be in the source server in info in our Discord Server & it's been kinda beat over the head for the past year there, but I completely understand not wanting/needing to join a server for info, esp since we've got the documentation site)

**Comment by CrimsonFork** [comment]
We see, thanks, ^^. (We also were plainly unaware a server exists {not that it's surprising}, although, yeah, probably wouldn't've joined anyway.)
