### ISSUE TITLE
403 code given for all avatars & no avatars showing up

### ISSUE THREAD

**Issue by laventown** [PluralKit/PluralKit#610]
![Screenshot 2024-02-07 110322](https://github.com/PluralKit/PluralKit/assets/159305051/5e5e6842-d651-4b43-bf21-f47d4e430df8)
![Screenshot 2024-02-07 110426](https://github.com/PluralKit/PluralKit/assets/159305051/3a2797da-9749-4335-9b57-95b19a1158ac)

basically, no matter the member: the image won't work. it's giving a 403 error, and the avatar isn't showing up. it works sometimes for some members in different servers, but it is very unpredictable and sometimes just stops working. i'm not sure if it's user error or a glitch, but i figured reporting it would be smart.

**Comment by multimasks** [comment]
Avatars not working turned out to be part of a larger Discord issue, and they are actively looking into it right now. The Discord Status page (https://discordstatus.com/# ) now has an incident report about it that you can go follow for updates from them.

**Comment by multimasks** [comment]
We're also working on the 403 error, since we think that's something separate (though still related)

**Comment by u1f408** [comment]
In future, issues like this should be asked about in the support server (https://discord.gg/PczBt78), not here!
