### ISSUE TITLE
Avatar issues 

### ISSUE THREAD

**Issue by Gh0stc0ll3ctive** [PluralKit/PluralKit#616]
I've come to notice recently when I set a new avatar that has said it's set and worked without a error hasn't shown up or most recently i set Simon a avatar for a server and it's had the same issue - John

**Comment by u1f408** [comment]
We know about issues with avatars - but this isn't the place to report them. Please ask in the support server (https://discord.gg/PczBt78) for issues like this, GitHub issues are for bugs/issues with the code.
