### ISSUE TITLE
[Feature] Add webhook API to notify services of switches

### ISSUE THREAD

**Issue by Lunaphied** [PluralKit/PluralKit#622]
Right now the only way for applications to learn about switches seems to be to poll PluralKit's API endpoints regularly to see if it's changed. This quickly runs afoul of rate limits and scales poorly if you want to update relatively promptly and have more than a handful of clients that wish to request the information. 

If PluralKit could instead directly notify consumers via a webhook or similar this would make such designs significantly easier.

**Comment by u1f408** [comment]
This already exists: https://pluralkit.me/api/dispatch/

**Comment by Lunaphied** [comment]
Ah huh, I missed that somehow thank you!
