### ISSUE TITLE
User-installed App Support to allow command use in DMs?

### ISSUE THREAD

**Issue by ntseng** [PluralKit/PluralKit#633]
Are there plans to support user-installs on the app (https://discord.com/developers/docs/tutorials/developing-a-user-installable-app)? This looks like it would allow users who've installed PluralKit onto their discord account to use commands in DMs.

It does seem like that functionality might require slash commands. I'd be happy to help out with development, but would need some onboarding because most of my bot development is in JS.

**Comment by ntseng** [comment]
Ah, ok. Thanks for the response!

**Comment by AetherCollective** [comment]
D-Proxy has managed to figure out how to do user-installed apps with working proxies in DMs. Maybe someone from the dev team could reach out and see how they are doing it and see if it could be implemented.
