### ISSUE TITLE
Rotating Avatars

### ISSUE THREAD

**Issue by sisby-folk** [PluralKit/PluralKit#639]
Forwarding an niche and complex request - being able to set multiple avatars, and have them display based on time (e.g. cycling forward once a day). Would require restructuring the model, but hey, maybe there's some other idea that would require the same thing.

**Comment by u1f408** [comment]
This is *way* out of scope for being implemented in the bot itself, sorry.

That said, it'd be fairly trivial to do this using the [PluralKit API](https://pluralkit.me/api/) and a script on your own machine that changes the member avatar URL on a schedule.
