### ISSUE TITLE
Add system config option to not put a space between member display name and system tag?

### ISSUE THREAD

**Issue by Tachytaenius** [PluralKit/PluralKit#667]
Found the code that does the appending here: https://github.com/PluralKit/PluralKit/blob/601d2660633d7d5b2a0bddcbcefa058d60d04bd3/PluralKit.Core/Database/Functions/ProxyMember.cs#L40-L43

Because some might want to have names separated Only by symbols. Something something unix terminals where username and hostname are separated by an @ something something :3c

**Comment by Tachytaenius** [comment]
The "tag changed (using x/79 characters)" would need to say 80 instead of 79 if spaces are disabled, wouldn't it

**Comment by xSke** [comment]
Personally I would prefer this get implemented as part of the name formatting feature that's been discussed over and over for years. So, wary of an "interim" config option to cover one use case vs. a more generic solution that covers many more, that we know will get obsoleted eventually.

But given how that's been stuck in "no one has bothered"-hell for a long time, maybe just configuring the separator is enough, and we can consider migration later?
